### ISSUE TITLE
Usulan Field yang wajib diisi pada form Submit

### ISSUE THREAD

**Issue by masharis** [lhfazry/Sekolah-Sunnah#15]
Usulan Field yang wajib diisi pada form Submit

nama sekolah
Kota
Alamat Lengkap
Uang masuk
Biaya bulanan
No Telp 1

dan pada bagian atas form dituliskan seperti ini:
"Jika lembaga Pendidikan mempunyai beberapa jenjang, mohon diisikan secara terpisah"

@lhfazry

**Comment by lhfazry** [comment]
fixed
