### ISSUE TITLE
ordering error

### ISSUE THREAD

**Issue by fitra68** [lhfazry/Sekolah-Sunnah#17]
fungsi order tabel hanya ngefek ke page list yang lagi tampil (10 row). Tidak ke semua row

**Comment by klanjabrik** [comment]
@fitra68 ini di halaman apa yah mas?

**Comment by fitra68** [comment]
di sini https://sekolahsunnah.com/admin/schools

**Comment by klanjabrik** [comment]
Ini sepertinya sudah diperbaiki.

**Comment by klanjabrik** [comment]
Maaf. ta reopen, ada beberapa column yang belum bekerja dengan semestinya.
