### ISSUE TITLE
jumlah entry tabel bisa diatur

### ISSUE THREAD

**Issue by fitra68** [lhfazry/Sekolah-Sunnah#18]
fungsi untuk mengatur jumlah row yang ditampilkan di sebuah tabel supaya diaktifkan, jadi fleksibel tidak hanya 10

**Comment by camagenta** [comment]
ini maksudnya yang beginian ya om?

![image](https://user-images.githubusercontent.com/2554004/65414321-a844a680-de1d-11e9-857e-526a05cd7468.png)

**Comment by fitra68** [comment]
iyes
