### ISSUE TITLE
Jangan izinkan isi biaya masuk dan bulanan 0.

### ISSUE THREAD

**Issue by masharis** [lhfazry/Sekolah-Sunnah#22]
Jangan izinkan isi biaya masuk dan bulanan 0. 

di data ada beberapa yg submit dengan angka 0

**Comment by camagenta** [comment]
ini masih bingung caranya, aku belajarnya lewat [malasngoding-18](https://www.malasngoding.com/membuat-form-validasi-pada-laravel/) dia ada di controller. @lhfazry kayane gak make ini.

abis baca ini [Tiga Cara Memvalidasi Form di Laravel](https://medium.com/laravel-web-id/tiga-cara-memvalidasi-form-di-laravel-3fb566067cd0) baru nggeh ada metode lain, kayak di CI dulu dia bisa buat config untuk rule validasi form di form_validation.

dan rulenya fazry untuk sekolah ini ada di [app\Models\School.php](https://github.com/lhfazry/Sekolah-Sunnah/blob/master/app/Models/School.php#L168)

`public static $rules = [
        'nama_sekolah' => 'required',
        'level_id' => 'required',
        'city_id' => 'required',
        'biaya_pendaftaran' => 'required',
        'biaya_spp' => 'required',
        'address' => 'required',
        'phone1' => 'required',
        'contact_person' => 'required',
        'hp' => 'required'
    ];

    public static $messages = [
        'nama_sekolah.required' => 'Nama Sekolah tidak boleh kosong',
        'level_id.required' => 'Jenjang tidak boleh kosong',
        'city_id.required' => 'Kota tidak boleh kosong',
        'biaya_pendaftaran.required' => 'Uang masuk tidak boleh kosong',
        'biaya_spp.required' => 'Biaya bulanan tidak boleh kosong',
        'address.required' => 'Alamat tidak boleh kosong',
        'phone1.required' => 'Telpon 1 tidak boleh kosong',
        'contact_person.required' => 'Contact Person tidak boleh kosong',
        'hp.required' => 'Nomor HP tidak boleh kosong',
    ];`
