### ISSUE TITLE
URL shortener untuk tampilan readability yang lebih baik

### ISSUE THREAD

**Issue by adityasiregar2019** [lhfazry/Sekolah-Sunnah#24]
Untuk pengelola sekolah agar dapat men share site mereka via medsos misal FB/WA dengan tampilan yang enak dan tidak kepanjangan maka diperlukan readability link yang bagus, misal Ponpes Darut Taqwa link nya adalah : 

https://sekolahsunnah.com/detail/eyJpdiI6IkJqbDJSZ0VIQXZvak5uNGdWa2c4RkE9PSIsInZhbHVlIjoiZVZRdXlcLytrRlFnK0o4WlwvbEswVFFBPT0iLCJtYWMiOiJmNWRhNDIwM2NkYjFmN2I4NWJkMDI5NzUzZGE3ZGNhMDJjYjY1MjQ0ZDJhNGFjZGZhYjhmM2VhNjFmMjEzNTM4In0=

Kalau bisa ada menu untuk URL shortener dengan tetap mempertahankan nama sekolahsunnah.com nya.

Misal ini situ s UGM , darut taqwa disingkat menjadi :
http://ugm.id/daruttaqwa

**Comment by camagenta** [comment]
usul yang terakhir pake slug, link-nya kayak model encrypt jadi gak readable
