### ISSUE TITLE
gambar default untuk sekolah yang belum upload gambar

### ISSUE THREAD

**Issue by camagenta** [lhfazry/Sekolah-Sunnah#28]
sekolah yang belum upload foto tampilan preview-nya blank kayak gini

![image](https://user-images.githubusercontent.com/2554004/65415139-569d1b80-de1f-11e9-8fda-91bfb82b0f7b.png)

ahsan sih dibuat gambar default aja. apa kek gtu. kepikirannya dibuat khusus tau gambar depan yang al quran itu aja di pake. hehe

**Comment by klanjabrik** [comment]
Kalau pake background colornya aja gimana om @camagenta ? (Tolong lihat gambar terlampir)
<img width="299" alt="Screen Shot 2019-09-25 at 16 48 30" src="https://user-images.githubusercontent.com/403877/65590116-6c901500-dfb4-11e9-94ec-dd54d51fa196.png">

**Comment by camagenta** [comment]
boleh, biar gak terkesan gak ada gambar aja. kalo warna abu itu kayak gmn gtu lihatnya
