### ISSUE TITLE
Tampilan home yang user friendly

### ISSUE THREAD

**Issue by camagenta** [lhfazry/Sekolah-Sunnah#44]
Ada masukan soal text di halaman depan belum user friendly. Perlu di running dikit

![Screenshot_2019-09-30-05-37-26-147_com android chrome](https://user-images.githubusercontent.com/2554004/65839918-90e94a00-e344-11e9-8d18-0bf79c072188.png)

**Comment by klanjabrik** [comment]
* [ ] Di mobile: Scroll pada detail sekolah akan terhambar jika sampai peta, perlu pengkondisian
