### ISSUE TITLE
Jenis font pada editor WYIWYG tidak terlihat dengan jelas

### ISSUE THREAD

**Issue by klanjabrik** [lhfazry/Sekolah-Sunnah#5]
<img width="262" alt="Screen Shot 2019-08-16 at 11 06 31" src="https://user-images.githubusercontent.com/403877/63142925-1b385180-c016-11e9-96f3-e93e8494eaef.png">

### Device
Browser: Chrome 76.0
OS: Mojave

**Comment by lhfazry** [comment]
fixed
