### ISSUE TITLE
other school sesuai jenjang

### ISSUE THREAD

**Issue by camagenta** [lhfazry/Sekolah-Sunnah#51]
posisi other school sepertinya saat ini masih bebas

![image](https://user-images.githubusercontent.com/2554004/65955421-4cf46300-e472-11e9-8838-f4555e123a10.png)

usul perbaikan, ketika melihat detail sekolah.. info other school ini sama jenjangnya. tidak asal sekolah lainnya.

**Comment by camagenta** [comment]
contoh di atas profil TK, tapi info sekolah lainnya ada SMA dan SMP

rasane kok risih yo... ra pas

**Comment by camagenta** [comment]
pagi ini nemu yang lebih ekstrim lagi,

gak cuman yang sesuai jenjang, tapi yang terdekat secara lokasi

![image](https://user-images.githubusercontent.com/2554004/66532269-01f4e280-eb39-11e9-9022-d19550658179.png)

**Comment by klanjabrik** [comment]
Kalau dibuat yang terdekat sepertinya belum memungkinkan, sementara dibuat yang memiliki kesamaan di jenjang pendidikan dan kota (jika ada).

**Comment by camagenta** [comment]
Mantap. Begitu dulu sudah ok

**Comment by klanjabrik** [comment]
Alhamdulillaah. Sudah dimasukkan ke pull request terbaru.
