### ISSUE TITLE
Error saat menambahkan foto ke 5 

### ISSUE THREAD

**Issue by masharis** [lhfazry/Sekolah-Sunnah#8]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'photo5' in 'field list' (SQL: update `schools` set `photo5` = photos/1565940060_WhatsApp Image 2019-08-15 at 09.59.54 (1).jpeg, `schools`.`updated_at` = 2019-08-16 07:21:02 where `id` = 36)
![scrnli_8_16_2019_2-21-54 PM](https://user-images.githubusercontent.com/2518924/63150567-51cf9580-c031-11e9-8469-c192fdb6e491.png)

**Comment by lhfazry** [comment]
fixed
